# Generated by Django 4.1.1 on 2022-10-12 19:55

import datetime
import django.core.validators
from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"first_name" field value less than two symbols')], verbose_name='first name')),
                ('last_name', models.CharField(error_messages={'min_length': '"last_name" field value less than two symbols'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('email', models.EmailField(max_length=254, validators=[core.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@test.com'), core.validators.validate_unique_email])),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[core.validators.validate_phone_number])),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
