# Generated by Django 4.1.1 on 2022-10-01 22:34

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@test.com')]),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
