# Generated by Django 4.1.1 on 2022-10-08 20:38

from django.db import migrations, models
import phonenumber_field.modelfields
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@test.com'), students.validators.validate_unique_email]),
        ),
    ]
