# Generated by Django 4.1.1 on 2022-10-08 21:24

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_phone_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[students.validators.validate_phone_number]),
        ),
    ]
