# Generated by Django 4.1.1 on 2022-10-08 21:29

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[students.validators.validate_phone_number]),
        ),
    ]
