# Generated by Django 4.1.1 on 2022-10-09 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"first name" field value less than two symbols')], verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"last name" field value less than two symbols')], verbose_name='last name')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
