# Generated by Django 4.1.1 on 2022-10-02 21:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(db_column="group's name", max_length=50, validators=[django.core.validators.MinLengthValidator(2, '"name_of_group" field value less than two symbols')], verbose_name="group's name")),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('group_description', models.TextField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
