# Generated by Django 4.1.1 on 2022-10-18 20:13

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.datetime.utcnow, validators=[groups.validators.validate_start_date])),
                ('end_date', models.DateField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('group_description', models.TextField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
