# Generated by Django 4.1.1 on 2022-10-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0002_group_headman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_description',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses.course'),
        ),
    ]
